title: The MAT Association
description: Empowering the next generation of champions.

theme: jekyll-theme-slate
# theme: jekyll-theme-hacker
# theme: jekyll-theme-architect
# theme: jekyll-theme-dinky
# theme: jekyll-theme-midnight
# theme: jekyll-theme-minimal
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-merlot


plugins:
  - jekyll-seo-tag
