title: The MAT Association
description: Empowering the next generation of champions.

theme: pages-themes/cayman@v0.2.0
# theme: pages-themes/slate
# theme: pages-themes/hacker
# theme: pages-themes/architect
# theme: pages-themes/time-machine
# theme: pages-themes/dinky

plugins:
  - jekyll-seo-tag
